# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js?hacstag=<12345678901>

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 90

logger:
  filters:
    moonraker_api.websockets.websocketclient:
      - ".*Websocket connection error: Cannot connect to host*"

# My Additiona
homeassistant:
  allowlist_external_dirs:
    - "/media/ReolinkSnapshot/"
  packages:
    pack_1: !include pack_notify.yaml
    pack_2: !include pack_helpers.yaml
    pack_3: !include pack_unavailable_entities.yaml
    pack_4: !include pack_waveshare_epaper_6625d8.yaml
#    pack_5: !include pack_ai.yaml

wake_on_lan:
